let GET_USERS = 'GET_USERS';
let GET_USER = 'GET_USER';
let ADD_USER = 'ADD_USER';
let UPDATE_USER = 'UPDATE_USER';
let DELETE_USER = 'DELETE_USER';

let GET_RESTORATIONS = 'GET_RESTORATIONS';
let GET_RESTORATION = 'GET_RESTORATION';
let GET_RESTORATIONS_FILTER = 'GET_RESTORATIONS_FILTER';

export {
    GET_USERS,
    GET_USER,
    ADD_USER,
    UPDATE_USER,
    DELETE_USER,
    GET_RESTORATIONS,
    GET_RESTORATION,
    GET_RESTORATIONS_FILTER
}
